name: CI pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md

  workflow_dispatch:

jobs:

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Secret Scanner
        uses: secret-scanner/action@0.0.2
        with:
          detect_secrets_version: 1.5.0

      - name: Install Terragrunt
        continue-on-error: false
        uses: eLco/setup-terragrunt@v1
        with:
          terragrunt_version: "0.75.3"

      - name: Install Terraform
        continue-on-error: false
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.1"

      - name: Check for basic formatting - terragrunt hclfmt
        run: make hclfmt-check

      - name: Check for basic formatting - terraform fmt
        run: make fmt-check