name: CI pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md

  workflow_dispatch:

jobs:

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Terragrunt
        continue-on-error: false
        uses: eLco/setup-terragrunt@v1
        with:
          terragrunt_version: "0.75.3"

      - name: Install Terraform
        continue-on-error: false
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.1"

      - name: Install tflint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
          
      - name: Check for basic formatting - terragrunt hclfmt
        run: make hclfmt-check

      - name: Check for basic formatting - terraform fmt
        run: make fmt-check

      - name: Check for tflint
        run: make tflint

      - name: Validate terraform files
        run: make validate

      - name: Install terraform-docs
        uses: supplypike/setup-bin@v4
        with:
          uri: https://github.com/terraform-docs/terraform-docs/releases/download/v0.19.0/terraform-docs-v0.19.0-linux-amd64.tar.gz
          name: terraform-docs
          version: 0.19.0

      - name: Validate whether tfdocs are up-to-date
        run: make tfdocs-check

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: modules/
          skip_check: CKV_AZURE_59,CKV_AZURE_190
          quiet: true
          framework: terraform
          output_format: sarif
          download_external_modules: false 
          log_level: DEBUG
